project_id = "zihohzstvbdobxahjfsy"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"

[functions.request-cv]
verify_jwt = false

[functions.check-cv-status]
verify_jwt = false

[functions.chat-assistant]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.notify-cv-approval]
verify_jwt = false

[functions.resend-webhook]
verify_jwt = false
